# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    format_listener:
        rules:
            - { path: ^/v1/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }

